spring:

  # DB 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddlAuto: update

# File Upload 경로
file:
  # upload.path: E:/[uploads]/
  upload.path: D:/uploads/
  upload.url: /uploads/